name: opencc_sdk_example
description: "Demonstrates how to use the opencc_sdk plugin."
publish_to: 'none' 
version: 1.0.0+1000001

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  opencc_sdk:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
